/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project2;

import SanPham.SanPham_bill;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Photocopy HoaQuan
 */
public class bill extends javax.swing.JFrame {
    
    /**
     * Creates new form bill
     */
    
    
    
    ArrayList<SanPham_bill> sp_bill = new ArrayList<SanPham_bill>();
    DefaultTableModel table;
    int dong = 0;
    
    public void LoadDataForTable_bill(){
    sp_bill.clear();
        try{
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project2","root","");
                String sql = "SELECT * FROM bill";    
                PreparedStatement stmt = conn.prepareStatement(sql);
                    ResultSet rs = stmt.executeQuery();
                    sp_bill.clear();
                    while(rs.next()){
                        String SoHoaDon = rs.getString(2);
                        String NgayLap = rs.getString(3);
                        int MaNhanVien = rs.getInt(4);
                        String MaSanPham = rs.getString(5);
                        String TenKhach = rs.getString(6);
                        String SoDienThoai = rs.getString(7);
                        String Tong = rs.getString(8);
                        String GhiChu = rs.getString(9);
                        
                        SanPham_bill spham= new SanPham_bill(SoHoaDon, NgayLap, MaNhanVien,MaSanPham, TenKhach,SoDienThoai, Tong,GhiChu);
                        sp_bill.add(spham);
                    }
                    conn.close();
                    
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    
    public void LoadDataArrayListToTable_bill(){
        table = (DefaultTableModel) tbl_bill.getModel();
        table.setRowCount(0);
        for(SanPham_bill s: sp_bill){
            table.addRow(new Object[]{table.getRowCount() + 1,s.getSoHoaDon(),s.getNgayLap(),s.getMaSanPham(),s.getTenKhach(),s.getSoDienThoai(),s.getTong(),s.getGhiChu()});
        }
    }
    private int id;
    public void bill(int id){
        this.id = id;
        
    }
    
    public bill() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        LoadDataForTable_bill();
        LoadDataArrayListToTable_bill();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_bill = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnCapNhap = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnTruoc = new javax.swing.JButton();
        btnSau = new javax.swing.JButton();
        btnTrangChu = new javax.swing.JButton();
        btnChiTietHoaDon = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSoHoaDon = new javax.swing.JTextField();
        txtNgayLap = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTenSanPham = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTenKhach = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTong = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Hóa Đơn");

        tbl_bill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Số Hóa Đơn", "Ngày Lập", "Mã SP", "Tên Khách", "Số Điện Thoại", "Khách Trả", "Ghi Chú"
            }
        ));
        tbl_bill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_billMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_bill);

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnCapNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/updated.png"))); // NOI18N
        btnCapNhap.setText("Cập Nhập");
        btnCapNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhapActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset.png"))); // NOI18N
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnTruoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/arrow-button.png"))); // NOI18N
        btnTruoc.setText("Sau");
        btnTruoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruocActionPerformed(evt);
            }
        });

        btnSau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/next-button.png"))); // NOI18N
        btnSau.setText("Trước");
        btnSau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSauActionPerformed(evt);
            }
        });

        btnTrangChu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/house.png"))); // NOI18N
        btnTrangChu.setText("  Trang Chủ");
        btnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChuActionPerformed(evt);
            }
        });

        btnChiTietHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnChiTietHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/detail1.png"))); // NOI18N
        btnChiTietHoaDon.setText("Chi Tiết Hóa Đơn");
        btnChiTietHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietHoaDonActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/log-out.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seach.png"))); // NOI18N
        jLabel8.setText("Tìm Kiếm:");

        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setText("Số Hóa Đơn");

        jLabel3.setText("Ngày Lập");

        jLabel4.setText("Mã Sản Phẩm");

        jLabel5.setText("Tên khách");

        jLabel7.setText("Số Điện Thoại");

        jLabel6.setText("Khách Trả");

        txtTong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phương Thức Thanh Toán", "Chuyển Khoản", "Tiền Mặt" }));

        jLabel9.setText("Ghi chú");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTong, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNgayLap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(txtSoHoaDon, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenSanPham))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTenKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel1)
                .addGap(126, 394, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTrangChu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnChiTietHoaDon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTruoc, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnCapNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnSau, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(21, 21, 21)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChiTietHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(115, 115, 115))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnCapNhap))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXoa)
                            .addComponent(btnLamMoi))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTruoc)
                            .addComponent(btnSau))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        try{
            if(txtSoHoaDon.getText().equals("")){
                txtSoHoaDon.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Số hóa đơn không được để trống");
            }else{
                 if(JOptionPane.showConfirmDialog(this, "Bạn muốn thêm chứ :3")== JOptionPane.YES_OPTION){
                txtSoHoaDon.setBackground(Color.white);
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project2","root","");
                String sql1 = "SELECT * FROM bill where SoHoaDon = ? ";    
                PreparedStatement stmt = conn.prepareStatement(sql1);
                    
                    stmt.setString(1, txtSoHoaDon.getText());
                    ResultSet rs = stmt.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "Đã có số hóa đơn nầy");
                }else{
                
                
                String sql = "INSERT INTO bill(ID_bill,SoHoaDon,NgayLap,MaNhanVien,MaSanPham,TenKhach,SoDienThoai,Tong,GhiChu) VALUES(?,?,?,?,?,?,?,?,?)";    
                PreparedStatement stmt1 = conn.prepareStatement(sql);
                    stmt1.setString(1, null);
                    stmt1.setString(2, txtSoHoaDon.getText());
                    stmt1.setString(3, txtNgayLap.getText());
                    stmt1.setInt(4,id);
                    stmt1.setString(5, txtTenSanPham.getText());
                    stmt1.setString(6, txtTenKhach.getText());
                    stmt1.setString(7, txtSoDienThoai.getText());
                    stmt1.setString(8, txtTong.getSelectedItem().toString());
                    stmt1.setString(9, txtGhiChu.getText());
                    stmt1.execute();
                    JOptionPane.showMessageDialog(null, "Thêm thành công");
                    
                        String SoHoaDon = txtSoHoaDon.getText();
                        String NgayLap = txtNgayLap.getText();
                        int MaNhanVien =id;
                        String MaSanPham = txtTenSanPham.getText();
                        String TenKhach = txtTenKhach.getText();
                        String SoDienThoai = txtSoDienThoai.getText();
                        String Tong = txtTong.getSelectedItem().toString();
                        String GhiChu = txtGhiChu.getText();
                        
                        
                        SanPham_bill spham = new SanPham_bill(SoHoaDon, NgayLap, MaNhanVien,MaSanPham, TenKhach,SoDienThoai, Tong,GhiChu);
                    sp_bill.add(spham);
                    LoadDataForTable_bill();
                    LoadDataArrayListToTable_bill();
                    this.pack();
            
                    }
                conn.close();
            }
            
            else{
                return;
                }
            }
            
        }catch(SQLException ex){
        
            }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnCapNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhapActionPerformed
        // TODO add your handling code here:
        try{
            if(txtSoHoaDon.getText().equals("")){
                txtSoHoaDon.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Số hóa đơn không được để trống");
                txtSoHoaDon.setBackground(Color.white);
            }else{
                if(JOptionPane.showConfirmDialog(this, "Bạn muốn cập nhập chứ ?")== JOptionPane.YES_OPTION){
                txtSoHoaDon.setBackground(Color.white);
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project2","root","");
                String sql1 = "SELECT * FROM bill where SoHoaDon = ?";    
                PreparedStatement stmt1 = conn.prepareStatement(sql1);
                    
                    stmt1.setString(1, txtSoHoaDon.getText());
                    ResultSet rs = stmt1.executeQuery();
                if(rs.next()){
                //Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project2","root","");
                String sql = "Update bill set  NgayLap = ?,TenKhach = ?,MaSanPham = ?, SoDienThoai = ?,Tong=?,GhiChu = ? WHERE SoHoaDon = ?"  ;    
                PreparedStatement stmt = conn.prepareStatement(sql);
                    
                    
                    stmt.setString(7, txtSoHoaDon.getText());
                    stmt.setString(1, txtNgayLap.getText());
                    stmt.setString(2, txtTenKhach.getText());
                    stmt.setString(3, txtTenSanPham.getText());
                    stmt.setString(4, txtSoDienThoai.getText());
                    stmt.setString(5, txtTong.getSelectedItem().toString());
                    stmt.setString(6, txtGhiChu.getText());
                    //System.out.println(""+stmt);
                    stmt.execute();
                    
           JOptionPane.showMessageDialog(null, "Cập nhập thành công");
           LoadDataForTable_bill();
           LoadDataArrayListToTable_bill();
           this.pack();
            
            conn.close();
                }else{
                    JOptionPane.showMessageDialog(null, "Không có!");
                }
            }else{
                return;
                
            }
            }
        }catch(SQLException ex){
        
            }
    }//GEN-LAST:event_btnCapNhapActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        try{
            if(txtSoHoaDon.getText().equals("")){
                txtSoHoaDon.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Số hóa đơn không được để trống");
            }
            else{
            if(JOptionPane.showConfirmDialog(this, "Bạn chắc chưa?")== JOptionPane.YES_OPTION){
                txtSoHoaDon.setBackground(Color.white);
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project2","root","");
                String sql1 = "SELECT * FROM bill where SoHoaDon = ?";    
                PreparedStatement stmt1 = conn.prepareStatement(sql1);
                    
                    stmt1.setString(1, txtSoHoaDon.getText());
                    ResultSet rs = stmt1.executeQuery();
                if(rs.next()){
                txtSoHoaDon.setBackground(Color.white);
                //Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project2","root","");
                String sql = "DELETE FROM bill WHERE SoHoaDon = ?";
                PreparedStatement stmt = conn.prepareStatement(sql);
                    stmt.setString(1, txtSoHoaDon.getText());
                    
//                    System.out.println(""+stmt1);
                    stmt.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Xóa thành công");
                    LoadDataForTable_bill();
                    LoadDataArrayListToTable_bill();
                    this.pack();
            
            conn.close();
                }else{
                JOptionPane.showMessageDialog(null, "Không có!");
                }
            }
            else{
                return;
                
            }
            }
        }catch(SQLException ex){
        
            }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
            txtSoHoaDon.setText("");
            txtNgayLap.setText("");
            txtTenSanPham.setText("");
            txtTenKhach.setText("");
            txtSoDienThoai.setText("");
            txtTong.setSelectedItem("");
            txtGhiChu.setText("");
            LoadDataForTable_bill();
           LoadDataArrayListToTable_bill();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnTruocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruocActionPerformed
        // TODO add your handling code here:
        dong++;
        if(dong>= sp_bill.size()){
            JOptionPane.showConfirmDialog(null, "nhìn bảng chưa mà ấn!!!");
            return;
        }
        hienthi(dong);
        tbl_bill.setRowSelectionInterval(dong, dong);
    }//GEN-LAST:event_btnTruocActionPerformed

    private void tbl_billMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_billMouseClicked
        // TODO add your handling code here:
        dong = tbl_bill.getSelectedRow();
        hienthi(dong);
    }//GEN-LAST:event_tbl_billMouseClicked

    private void btnSauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSauActionPerformed
        // TODO add your handling code here:
        dong--;
        if(dong < 0){
            JOptionPane.showConfirmDialog(null, "Bạn đang ở đầu chang!");
            return;
        }
//        if(dong==0){
//            JOptionPane.showConfirmDialog(null, "Không có sản phẩm nào");
//        }
        hienthi(dong);
        tbl_bill.setRowSelectionInterval(dong, dong);
    }//GEN-LAST:event_btnSauActionPerformed

    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChuActionPerformed
        // TODO add your handling code here:
        dispose();
        Information i = new Information();
        i.Information(id);
        i.show();
    }//GEN-LAST:event_btnTrangChuActionPerformed

    private void btnChiTietHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietHoaDonActionPerformed
        // TODO add your handling code here:
        dispose();
        detail_bill de = new detail_bill();
        de.detail(txtSoHoaDon.getText(),txtTenSanPham.getText(),id);
        de.LoadDataForTable_detailWhereBill(txtSoHoaDon.getText());
        de.show();
    }//GEN-LAST:event_btnChiTietHoaDonActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        // TODO add your handling code here:
        sp_bill.clear();
        try{
         
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project2","root","");
        String sql = "SELECT * FROM bill WHERE SoHoaDon LIKE N'%"+ txtTimKiem.getText()+"%'OR TenKhach LIKE N'%"+txtTimKiem.getText()+"%'";
        //String sql = "SELECT * FROM bill WHERE SoHoaDon LIKE N'%"+ txtTimKiem.getText()+"%'";
        PreparedStatement stmt = conn.prepareStatement(sql);
        ResultSet rs = stmt.executeQuery();
        System.out.println(""+stmt);
        while(rs.next()){
                        String SoHoaDon = rs.getString(2);
                        String NgayLap = rs.getString(3);
                        int MaNhanVien = rs.getInt(4);
                        String MaSanPham = rs.getString(5);
                        String TenKhach = rs.getString(6);
                        String SoDienThoai = rs.getString(7);
                        String Tong = rs.getString(8);
                        String GhiChu =rs.getString(9);
                        SanPham_bill spham= new SanPham_bill(SoHoaDon, NgayLap, MaNhanVien,MaSanPham, TenKhach,SoDienThoai, Tong,GhiChu);
                        sp_bill.add(spham);
                        
        }
        conn.close();
        
        LoadDataArrayListToTable_bill();
            
        }catch(SQLException e){
            //e.printStackTrace();
        }
    }//GEN-LAST:event_txtTimKiemKeyReleased

    public void hienthi(int dong){
    SanPham_bill spham = sp_bill.get(dong);
        txtSoHoaDon.setText(spham.getSoHoaDon());
        txtNgayLap.setText(spham.getNgayLap());
        txtTenSanPham.setText(spham.getMaSanPham());
        txtTenKhach.setText(spham.getTenKhach());
        txtSoDienThoai.setText(spham.getSoDienThoai());
        txtTong.setSelectedItem(spham.getTong());
        txtGhiChu.setText(spham.getGhiChu());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhap;
    private javax.swing.JButton btnChiTietHoaDon;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSau;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTrangChu;
    private javax.swing.JButton btnTruoc;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_bill;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtNgayLap;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtSoHoaDon;
    private javax.swing.JTextField txtTenKhach;
    private javax.swing.JTextField txtTenSanPham;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JComboBox<String> txtTong;
    // End of variables declaration//GEN-END:variables
}
