/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project2;

import SanPham.SanPham;
import java.awt.Color;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Photocopy HoaQuan
 */
public class manager extends javax.swing.JFrame {
    
    /**
     * Creates new form manager
     */
    DefaultTableModel tabtable;
    int dong = 0;
    ArrayList<SanPham> sp = new ArrayList<SanPham>();
    public void LoadDataForTable(){
        sp.clear();
        try{
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project2","root","");
                String sql = "SELECT * FROM information";    
                PreparedStatement stmt = conn.prepareStatement(sql);
                    ResultSet rs = stmt.executeQuery();
                    sp.clear();
                    while(rs.next()){
                        String MaSanPham = rs.getString(2);
                        String TenSanPham = rs.getString(3);
                        String KichCo = rs.getString(4);
                        String SoLuong = rs.getString(5);
                        String NgayNhap = rs.getString(6);
                        String NhaCungCap = rs.getString(7);
                        String GiaNhap = rs.getString(8);
                        String GiaBan = rs.getString(9);
                        SanPham spham= new SanPham(MaSanPham, TenSanPham, KichCo, SoLuong, NgayNhap,NhaCungCap, GiaNhap, GiaBan);
                        sp.add(spham);
                    }
                    conn.close();
                    
        }catch(Exception ex){
            ex.printStackTrace();
        }
        
        
    }
    
    public void LoadDataArrayListToTable(){
        tabtable = (DefaultTableModel) tblmanager.getModel();
        tabtable.setRowCount(0);
        for(SanPham s: sp){
            tabtable.addRow(new Object[]{tabtable.getRowCount() + 1,s.getMaSanPham(),s.getTenSanPham(),s.getSoLuong(),s.getNgayNhap(),s.getNhaCungCap(),s.getGiaNhap(),s.getGiaBan(),s.getKichCo()});
        }
    }
    private int id;
    public void manager(int id){
        this.id = id;
        
    }
    
    public manager() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        LoadDataForTable();
        LoadDataArrayListToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblmanager = new javax.swing.JTable();
        txtMaSanPham = new javax.swing.JTextField();
        txtSanPham = new javax.swing.JTextField();
        txtKichCo = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        txtNgayNhap = new javax.swing.JTextField();
        txtNhaCungCap = new javax.swing.JTextField();
        txtGiaNhap = new javax.swing.JTextField();
        txtGiaBan = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnBackTable = new javax.swing.JButton();
        txtSeach = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setText("Quản lý Thời Trang");

        jLabel2.setText("Mã Sản Phẩm");

        jLabel3.setText("Tên Sản Phẩm");

        jLabel4.setText("Ghi Chú");

        jLabel5.setText("Số Lượng");

        jLabel6.setText("Ngày Nhập");

        jLabel7.setText("Nhà Cung cấp");

        jLabel8.setText("Giá Nhập");

        jLabel9.setText("Giá Bán");

        tblmanager.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Sản Phẩm", "Tên Sản Phẩm", "Số Lượng", "Ngày Nhập", "Nhà Cung Cấp", "Giá Nhập", "Giá Bán", "Ghi Chú"
            }
        ));
        tblmanager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblmanagerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblmanager);

        txtSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSanPhamActionPerformed(evt);
            }
        });

        btnInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        btnInsert.setText("Thêm Mới");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/updated.png"))); // NOI18N
        btnUpdate.setText("Cập Nhập");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset.png"))); // NOI18N
        btnReset.setText("Làm Mới");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnHome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/house.png"))); // NOI18N
        btnHome.setText("Trang Chủ");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/arrow-button.png"))); // NOI18N
        btnNext.setText("Sau");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/log-out.png"))); // NOI18N
        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnBackTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/next-button.png"))); // NOI18N
        btnBackTable.setText("Trước");
        btnBackTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackTableActionPerformed(evt);
            }
        });

        txtSeach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeachActionPerformed(evt);
            }
        });
        txtSeach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSeachKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seach.png"))); // NOI18N
        jLabel10.setText("Tìm Kiếm:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnInsert)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBackTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtKichCo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(208, 208, 208)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSeach, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(btnHome)
                                .addGap(79, 79, 79)
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 176, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSeach, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtKichCo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInsert)
                            .addComponent(btnUpdate)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReset)
                            .addComponent(btnDelete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNext)
                            .addComponent(btnBackTable)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHome)
                            .addComponent(btnExit))))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSanPhamActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        try{
            if(txtMaSanPham.getText().equals("")){
                txtMaSanPham.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Mã Sản Phẩm không được để trống");
            }else{
                 if(JOptionPane.showConfirmDialog(this, "Bạn muốn thêm chứ :3")== JOptionPane.YES_OPTION){
                txtMaSanPham.setBackground(Color.white);
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project2","root","");
                String sql1 = "SELECT * FROM information where MaSanPham = ?";    
                PreparedStatement stmt = conn.prepareStatement(sql1);
                    
                    stmt.setString(1, txtMaSanPham.getText());
                     System.out.println("a: "+stmt);
                    ResultSet rs = stmt.executeQuery();
                    if(rs.next()){
                    String sql2 = "SELECT * FROM information where NhaCungCap = ? TenSanPham = ?";    
                    PreparedStatement stmt2 = conn.prepareStatement(sql2);
                    stmt2.setString(1, txtNhaCungCap.getText());
                    stmt2.setString(2, txtSanPham.getText());
                    ResultSet rs2 = stmt2.executeQuery();
                    if(rs2.next()){
                    int SoLuongBanDau = rs.getInt(5);
                    int SoLuongThem = Integer.parseInt(txtSoLuong.getText());
                    int SoLuongMoi = SoLuongBanDau+SoLuongThem;
                    String sql = "Update information set SoLuong = ? WHERE MaSanPham = ?"  ;    
                PreparedStatement stmt1 = conn.prepareStatement(sql);
                    
                    
                    stmt1.setString(2, txtMaSanPham.getText());
                    stmt1.setInt(1, SoLuongMoi);
                    
                    stmt1.execute();
                }else{
                        JOptionPane.showMessageDialog(null, "Mã Sản Phẩm đã tồn tại");
                
            
                    }
                    }else{
                        String sql = "INSERT INTO information(IDSanPham,MaSanPham,TenSanPham,KichCo,SoLuong,NgayNhap,NhaCungCap,GiaNhap,GiaBan) VALUES(?,?,?,?,?,?,?,?,?)";    
                PreparedStatement stmt1 = conn.prepareStatement(sql);
                    stmt1.setString(1, null);
                    stmt1.setString(2, txtMaSanPham.getText());
                    stmt1.setString(3, txtSanPham.getText());
                    stmt1.setString(4, txtKichCo.getText());
                    stmt1.setString(5, txtSoLuong.getText());
                    stmt1.setString(6, txtNgayNhap.getText());
                    stmt1.setString(7, txtNhaCungCap.getText());
                    stmt1.setString(8, txtGiaNhap.getText());
                    stmt1.setString(9, txtGiaBan.getText());
                    stmt1.execute();
                    JOptionPane.showMessageDialog(null, "Thêm thành công");
                    
                    String MaSanPham = txtMaSanPham.getText();
                        String TenSanPham = txtSanPham.getText();
                        String KichCo = txtKichCo.getText();
                        String SoLuong = txtSoLuong.getText();
                        String NgayNhap = txtNgayNhap.getText();
                        String NhaCungCap = txtNhaCungCap.getText();
                        String GiaNhap = txtGiaNhap.getText();
                        String GiaBan = txtGiaBan.getText();
                        
                        SanPham spham1 = new SanPham(MaSanPham, TenSanPham, KichCo, SoLuong, NgayNhap, NhaCungCap, GiaNhap, GiaBan);
                    sp.add(spham1);
                    LoadDataForTable();
                    LoadDataArrayListToTable();
                    this.pack();
                    }
                    
                
                conn.close();
            }
            
            else{
                return;
                }
            }
            
        }catch(SQLException ex){
        
            }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try{
            if(txtMaSanPham.getText().equals("")){
                txtMaSanPham.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Mã Sản Phẩm không được để trống");
                txtMaSanPham.setBackground(Color.white);
            }else{
                if(JOptionPane.showConfirmDialog(this, "Bạn muốn sửa chứ ?")== JOptionPane.YES_OPTION){
                
                txtMaSanPham.setBackground(Color.white);
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project2","root","");
                String sql1 = "SELECT * FROM information where MaSanPham = ?";    
                PreparedStatement stmt = conn.prepareStatement(sql1);
                    
                    stmt.setString(1, txtMaSanPham.getText());
                    ResultSet rs = stmt.executeQuery();
                if(rs.next()){
                    
                //Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project2","root","");
                String sql = "Update information set TenSanPham = ?, KichCo = ?,SoLuong = ?,NgayNhap = ?,NhaCungCap=?, GiaNhap = ?,GiaBan=? WHERE MaSanPham = ?"  ;    
                PreparedStatement stmt1 = conn.prepareStatement(sql);
                    
                    
                    stmt1.setString(8, txtMaSanPham.getText());
                    stmt1.setString(1, txtSanPham.getText());
                    stmt1.setString(2, txtKichCo.getText());
                    stmt1.setString(3, txtSoLuong.getText());
                    stmt1.setString(4, txtNgayNhap.getText());
                    stmt1.setString(5, txtNhaCungCap.getText());
                    stmt1.setString(6, txtGiaNhap.getText());
                    stmt1.setString(7, txtGiaBan.getText());
                    stmt1.execute();
           JOptionPane.showMessageDialog(null, "Cập nhập thành công");
           LoadDataForTable();
           LoadDataArrayListToTable();
           this.pack();
            txtMaSanPham.setText("");
            txtSanPham.setText("");
            txtKichCo.setText("");
            txtSoLuong.setText("");
            txtNgayNhap.setText("");
            txtNhaCungCap.setText("");
            txtGiaNhap.setText("");
            txtGiaBan.setText("");
            conn.close();
                }else{
                    JOptionPane.showMessageDialog(null, "Không có mã sản phẩm nầy");
                }
            }else{
                return;
                
            }
            }
        }catch(SQLException ex){
        
            }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try{
            if(txtMaSanPham.getText().equals("")){
                txtMaSanPham.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Mã Sản Phẩm không được để trống");
            }
            else{
            if(JOptionPane.showConfirmDialog(this, "Bạn chắc chưa?")== JOptionPane.YES_OPTION){
                 txtMaSanPham.setBackground(Color.white);
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project2","root","");
                String sql1 = "SELECT * FROM information where MaSanPham = ?";    
                PreparedStatement stmt = conn.prepareStatement(sql1);
                    
                    stmt.setString(1, txtMaSanPham.getText());
                    ResultSet rs = stmt.executeQuery();
                if(rs.next()){
                txtMaSanPham.setBackground(Color.white);
                //Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project2","root","");
                String sql = "DELETE FROM information WHERE MaSanPham = ?";
                PreparedStatement stmt1 = conn.prepareStatement(sql);
                    stmt1.setString(1, txtMaSanPham.getText());
                    
//                    System.out.println(""+stmt1);
                    stmt1.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Xóa thành công");
                    LoadDataForTable();
                    LoadDataArrayListToTable();
                    this.pack();
            txtMaSanPham.setText("");
            txtSanPham.setText("");
            txtKichCo.setText("");
            txtSoLuong.setText("");
            txtNgayNhap.setText("");
            txtNhaCungCap.setText("");
            txtGiaNhap.setText("");
            txtGiaBan.setText("");
            conn.close();
            }
                else{
                JOptionPane.showMessageDialog(null, "Không có mã sản phẩm nầy");
            }
            }
            else{
                return;
                
            }
            }
        }catch(SQLException ex){
        
            }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
            txtMaSanPham.setText("");
            txtSanPham.setText("");
            txtKichCo.setText("");
            txtSoLuong.setText("");
            txtNgayNhap.setText("");
            txtNhaCungCap.setText("");
            txtGiaNhap.setText("");
            txtGiaBan.setText("");
            LoadDataForTable();
           LoadDataArrayListToTable();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        dispose();
        home i = new home();
        i.home(id);
        i.show();
    }//GEN-LAST:event_btnHomeActionPerformed

    public void hienthi(int dong){
        SanPham spham = sp.get(dong);
        txtMaSanPham.setText(spham.getMaSanPham());
        txtSanPham.setText(spham.getTenSanPham());
        txtKichCo.setText(spham.getKichCo());
        txtSoLuong.setText(spham.getSoLuong());
        txtNgayNhap.setText(spham.getNgayNhap());
        txtNhaCungCap.setText(spham.getNhaCungCap());
        txtGiaNhap.setText(spham.getGiaNhap());
        txtGiaBan.setText(spham.getGiaBan());
    }
    
    private void tblmanagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblmanagerMouseClicked
        // TODO add your handling code here:
        dong = tblmanager.getSelectedRow();
        hienthi(dong);
    }//GEN-LAST:event_tblmanagerMouseClicked

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        dong++;
        if(dong>= sp.size()){
            JOptionPane.showConfirmDialog(null, "nhìn bảng chưa mà ấn!!!");
            return;
        }
        hienthi(dong);
        tblmanager.setRowSelectionInterval(dong, dong);
        
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnBackTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackTableActionPerformed
        // TODO add your handling code here:
        dong--;
        if(dong < 0){
            JOptionPane.showConfirmDialog(null, "Bạn đang ở cuối chang!");
            return;
        }
        hienthi(dong);
        tblmanager.setRowSelectionInterval(dong, dong);
    }//GEN-LAST:event_btnBackTableActionPerformed

    private void txtSeachKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSeachKeyReleased
        // TODO add your handling code here:
        sp.clear();
        try{
         
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project2","root","");
        String sql = "SELECT * FROM information WHERE TenSanPham LIKE N'%"+ txtSeach.getText()+"%' OR MaSanPham LIKE N'%"+txtSeach.getText()+"%'";
        
        PreparedStatement stmt = conn.prepareStatement(sql);
        ResultSet rs = stmt.executeQuery();
        System.out.println(""+stmt);
        while(rs.next()){
                        String MaSanPham = rs.getString(2);
                        String TenSanPham = rs.getString(3);
                        String KichCo = rs.getString(4);
                        String SoLuong = rs.getString(5);
                        String NgayNhap = rs.getString(6);
                        String NhaCungCap = rs.getString(7);
                        String GiaNhap = rs.getString(8);
                        String GiaBan = rs.getString(9);
                        SanPham sp1 = new SanPham(MaSanPham, TenSanPham, KichCo, SoLuong, NgayNhap, NhaCungCap, GiaNhap, GiaBan);
                        sp.add(sp1);
                        
        }
        conn.close();
        
        LoadDataArrayListToTable();
            
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_txtSeachKeyReleased

    private void txtSeachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeachActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackTable;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblmanager;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JTextField txtKichCo;
    private javax.swing.JTextField txtMaSanPham;
    private javax.swing.JTextField txtNgayNhap;
    private javax.swing.JTextField txtNhaCungCap;
    private javax.swing.JTextField txtSanPham;
    private javax.swing.JTextField txtSeach;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables
}
