/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project2;

import SanPham.SanPham_supplier;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
//import java.sql.*;
//import java.util.Date;
import java.sql.Date;
/**
 *
 * @author Photocopy HoaQuan
 */
public class supplier extends javax.swing.JFrame {

    /**
     * Creates new form supplier
     */
    
    
    ArrayList<SanPham_supplier> sp_supplier = new ArrayList<SanPham_supplier>();
    DefaultTableModel table;
    int dong = 0;
    
    public void LoadDataForTable_supplier(){
    sp_supplier.clear();
        try{
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project2","root","");
                String sql = "SELECT * FROM suppliers";    
                PreparedStatement stmt = conn.prepareStatement(sql);
                    ResultSet rs = stmt.executeQuery();
                    sp_supplier.clear();
                    while(rs.next()){
                        String MaNhaCungCap = rs.getString(2);
                        String TenNhaCungCap = rs.getString(3);
                        Date NgayKiHopDong = rs.getDate(4);
                        String DiaChi = rs.getString(5);
                        String Lienhe = rs.getString(6);
                        
                        SanPham_supplier spham= new SanPham_supplier(MaNhaCungCap, TenNhaCungCap, NgayKiHopDong, DiaChi, Lienhe);
                        System.out.println(""+NgayKiHopDong);
                        sp_supplier.add(spham);
                    }
                    conn.close();
                    
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    
    public void LoadDataArrayListToTable_supplier(){
     table = (DefaultTableModel) tblSupplier.getModel();
        table.setRowCount(0);
        for(SanPham_supplier s: sp_supplier){
            table.addRow(new Object[]{table.getRowCount() + 1,s.getMaNhaCungCap(),s.getTenNhaCungCap(),s.getNgayKiHopDong(),s.getDiaChi(),s.getLienHe()});
        }
    }
    private int id;
    public void supplier(int id) {
        this.id = id;
    }
    
    
    public supplier() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        LoadDataForTable_supplier();
        LoadDataArrayListToTable_supplier();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaNhaCungCap = new javax.swing.JTextField();
        txtTenNhaCungCap = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtLienHe = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSupplier = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnCapNhap = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnTruoc = new javax.swing.JButton();
        btnKeTiep = new javax.swing.JButton();
        btnTrangChu = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        txtNgayKiHopDong = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setText("Thông Tin Nhà Cung Cấp");

        jLabel2.setText("Mã Nhà Cung Cấp");

        jLabel3.setText("Tên Nhà Cung Cấp");

        jLabel4.setText("Ngày Kí Hợp Đồng");

        jLabel5.setText("Địa Chỉ");

        jLabel6.setText("Phương Thức Liên Lạc");

        tblSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Nhà Cung Cấp", "Tên Nhà Cung Cấp", "Ngày Kĩ Hợp Đồng", "Địa Chỉ", "Liên Hệ"
            }
        ));
        tblSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSupplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSupplier);
        if (tblSupplier.getColumnModel().getColumnCount() > 0) {
            tblSupplier.getColumnModel().getColumn(2).setResizable(false);
        }

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnCapNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/updated.png"))); // NOI18N
        btnCapNhap.setText("Cập Nhập");
        btnCapNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhapActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset.png"))); // NOI18N
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnTruoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/arrow-button.png"))); // NOI18N
        btnTruoc.setText("Trước");
        btnTruoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruocActionPerformed(evt);
            }
        });

        btnKeTiep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/next-button.png"))); // NOI18N
        btnKeTiep.setText("Kế Tiếp");
        btnKeTiep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeTiepActionPerformed(evt);
            }
        });

        btnTrangChu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/house.png"))); // NOI18N
        btnTrangChu.setText("Trang Chủ");
        btnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChuActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/log-out.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seach.png"))); // NOI18N
        jLabel7.setText("Tìm Kiếm:");

        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        txtNgayKiHopDong.setDateFormatString("dd-MM-yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(134, 134, 134)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnTruoc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaNhaCungCap)
                    .addComponent(txtTenNhaCungCap)
                    .addComponent(txtDiaChi)
                    .addComponent(txtLienHe)
                    .addComponent(btnCapNhap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKeTiep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNgayKiHopDong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(btnTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMaNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtTenNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtNgayKiHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtLienHe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(btnCapNhap))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnThem)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLamMoi)
                            .addComponent(btnXoa)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKeTiep)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTrangChu)
                        .addComponent(btnThoat))
                    .addComponent(btnTruoc))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        try{
            if(txtMaNhaCungCap.getText().equals("")){
                txtMaNhaCungCap.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Mã nhà cung Cấp không được để trống");
            }else{
                 if(JOptionPane.showConfirmDialog(this, "Bạn muốn thêm chứ :3")== JOptionPane.YES_OPTION){
                txtMaNhaCungCap.setBackground(Color.white);
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project2","root","");
                String sql = "SELECT * FROM suppliers where MaNhaCungCap = ?";    
                PreparedStatement stmt = conn.prepareStatement(sql);
                    
                    stmt.setString(1, txtMaNhaCungCap.getText());
                    ResultSet rs = stmt.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "Đã có mã nhà cung cấp nầy");
                }else{
                String ngayDat = txtNgayKiHopDong.getDateFormatString();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String sd = dateFormat.format(txtNgayKiHopDong.getDate());
            java.sql.Date date = Date.valueOf(sd);
                
                String sqlthem = "INSERT INTO suppliers(ID_NhaCungCap,MaNhaCungCap,TenNhaCungCap,NgayKiHopDong,DiaChi,LienHe) VALUES(?,?,?,?,?,?)";    
                PreparedStatement stmt1 = conn.prepareStatement(sqlthem);
                    stmt1.setString(1, null);
                    stmt1.setString(2, txtMaNhaCungCap.getText());
                    stmt1.setString(3, txtTenNhaCungCap.getText());
                    
                    stmt1.setString(4,date+"");
                    stmt1.setString(5, txtDiaChi.getText());
                    stmt1.setString(6, txtLienHe.getText());
                    //System.out.println(""+stmt1);
                    stmt1.execute();
                    JOptionPane.showMessageDialog(null, "Thêm thành công");
                    
                        String MaNhaCungCap = txtMaNhaCungCap.getText();
                        String TenNhaCungCap = txtTenNhaCungCap.getText();
                        
                        String DiaChi = txtDiaChi.getText();
                        String LienHe = txtLienHe.getText();
                        
                        SanPham_supplier spham = new SanPham_supplier(MaNhaCungCap, TenNhaCungCap, date, DiaChi, LienHe);
                    sp_supplier.add(spham);
                    LoadDataForTable_supplier();
                    LoadDataArrayListToTable_supplier();
                    this.pack();
            
                    }
                conn.close();
            }
            
            else{
                return;
                }
            }
            
        }catch(SQLException ex){
        
            }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnCapNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhapActionPerformed
        // TODO add your handling code here:
        try{
            if(txtMaNhaCungCap.getText().equals("")){
                txtMaNhaCungCap.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Mã nhà cung cấp không được để trống");
                txtMaNhaCungCap.setBackground(Color.white);
            }else{
                if(JOptionPane.showConfirmDialog(this, "Bạn muốn cập nhập chứ ?")== JOptionPane.YES_OPTION){
                
                txtMaNhaCungCap.setBackground(Color.white);
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project2","root","");
                String sql1 = "SELECT * FROM suppliers where MaNhaCungCap = ?";    
                PreparedStatement stmt1 = conn.prepareStatement(sql1);
                    
                    stmt1.setString(1, txtMaNhaCungCap.getText());
                    ResultSet rs = stmt1.executeQuery();
                if(rs.next()){
                    String ngayDat = txtNgayKiHopDong.getDateFormatString();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String sd = dateFormat.format(txtNgayKiHopDong.getDate());
            java.sql.Date date = Date.valueOf(sd);
                //Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project2","root","");
                String sql = "Update suppliers set  TenNhaCungCap = ?,NgayKiHopDong = ?,DiaChi = ?,LienHe = ? WHERE MaNhaCungCap = ?"  ;    
                PreparedStatement stmt = conn.prepareStatement(sql);
                    
                    
                    stmt.setString(5, txtMaNhaCungCap.getText());
                    stmt.setString(1, txtTenNhaCungCap.getText());
                    stmt.setString(2, date+"");
                    stmt.setString(3, txtDiaChi.getText());
                    stmt.setString(4, txtLienHe.getText());
                    System.out.println(""+stmt);
                    stmt.execute();
           JOptionPane.showMessageDialog(null, "Cập nhập thành công");
           LoadDataForTable_supplier();
           LoadDataArrayListToTable_supplier();
           this.pack();
            
            conn.close();
                }else{
                    JOptionPane.showMessageDialog(null, "Không có!");
                }
            }else{
                return;
                
            }
            }
        }catch(SQLException ex){
        
            }
    }//GEN-LAST:event_btnCapNhapActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        try{
            if(txtMaNhaCungCap.getText().equals("")){
                txtMaNhaCungCap.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Mã Nhà cung cấp không được để trống");
            }
            else{
            if(JOptionPane.showConfirmDialog(this, "Bạn chắc chưa?")== JOptionPane.YES_OPTION){
                if(JOptionPane.showConfirmDialog(this, "Bạn muốn cập nhập chứ ?")== JOptionPane.YES_OPTION){
                txtMaNhaCungCap.setBackground(Color.white);
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project2","root","");
                String sql1 = "SELECT * FROM suppliers where MaNhaCungCap = ?";    
                PreparedStatement stmt1 = conn.prepareStatement(sql1);
                    
                    stmt1.setString(1, txtMaNhaCungCap.getText());
                    ResultSet rs = stmt1.executeQuery();
                if(rs.next()){
                txtMaNhaCungCap.setBackground(Color.white);
                //Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project2","root","");
                String sql = "DELETE FROM suppliers WHERE MaNhaCungCap = ?";
                PreparedStatement stmt = conn.prepareStatement(sql);
                    stmt.setString(1, txtMaNhaCungCap.getText());
                    
//                    System.out.println(""+stmt1);
                    stmt.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Xóa thành công");
                    LoadDataForTable_supplier();
                    LoadDataArrayListToTable_supplier();
                    this.pack();
            
            conn.close();
                }else{
                    JOptionPane.showMessageDialog(null, "không có!");
                }}
            }
            else{
                return;
                
            }
            }
        }catch(SQLException ex){
        
            }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
            txtMaNhaCungCap.setText("");
            txtTenNhaCungCap.setText("");
//            txtNgayKiHopDong.setDate(""+1/1/2000);
            txtDiaChi.setText("");
            txtLienHe.setText("");
            
            LoadDataForTable_supplier();
            LoadDataArrayListToTable_supplier();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnTruocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruocActionPerformed
        // TODO add your handling code here:
        dong++;
        if(dong>= sp_supplier.size()){
            JOptionPane.showConfirmDialog(null, "nhìn bảng chưa mà ấn!!!");
            return;
        }
        hienthi(dong);
        tblSupplier.setRowSelectionInterval(dong, dong);
    }//GEN-LAST:event_btnTruocActionPerformed

    private void btnKeTiepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeTiepActionPerformed
        // TODO add your handling code here:
        dong--;
        if(dong < 0){
            JOptionPane.showConfirmDialog(null, "Bạn đang ở cuối chang!");
            return;
        }

        hienthi(dong);
        tblSupplier.setRowSelectionInterval(dong, dong);
    }//GEN-LAST:event_btnKeTiepActionPerformed

    private void tblSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSupplierMouseClicked
        // TODO add your handling code here:
        dong = tblSupplier.getSelectedRow();
        hienthi(dong);
    }//GEN-LAST:event_tblSupplierMouseClicked

    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChuActionPerformed
        // TODO add your handling code here:
        dispose();
        home i = new home();
        i.home(id);
        i.show();
    }//GEN-LAST:event_btnTrangChuActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        // TODO add your handling code here:
        sp_supplier.clear();
        try{
         
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project2","root","");
        String sql = "SELECT * FROM suppliers WHERE MaNhaCungCap LIKE N'%"+ txtTimKiem.getText()+"%'OR TenNhaCungCap LIKE N'%"+txtTimKiem.getText()+"%'";
        PreparedStatement stmt = conn.prepareStatement(sql);
        ResultSet rs = stmt.executeQuery();
        System.out.println(""+stmt);
        while(rs.next()){
                        String MaNhaCungCap = rs.getString(2);
                        String TenNhaCungCap = rs.getString(3);
                        Date NgayKiHopDong = rs.getDate(4);
                        String DiaChi = rs.getString(5);
                        String Lienhe = rs.getString(6);
                        System.out.println("000:"+NgayKiHopDong);
                        SanPham_supplier spham= new SanPham_supplier(MaNhaCungCap, TenNhaCungCap, NgayKiHopDong, DiaChi, Lienhe);
                        sp_supplier.add(spham);
                        
        }
        conn.close();
        
        LoadDataArrayListToTable_supplier();
            
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_txtTimKiemKeyReleased

    public void hienthi(int dong){
        SanPham_supplier spham = sp_supplier.get(dong);
        txtMaNhaCungCap.setText(spham.getMaNhaCungCap());
        txtTenNhaCungCap.setText(spham.getTenNhaCungCap());
        txtNgayKiHopDong.setDate(spham.getNgayKiHopDong());
        txtDiaChi.setText(spham.getDiaChi());
        txtLienHe.setText(spham.getLienHe());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new supplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhap;
    private javax.swing.JButton btnKeTiep;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTrangChu;
    private javax.swing.JButton btnTruoc;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSupplier;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtLienHe;
    private javax.swing.JTextField txtMaNhaCungCap;
    private com.toedter.calendar.JDateChooser txtNgayKiHopDong;
    private javax.swing.JTextField txtTenNhaCungCap;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
